`ifndef ETHMAC_PKG_SV
`define ETHMAC_PKG_SV

package ethmac_pkg;
  import uvm_pkg::*;
  `include "uvm_macros.svh"

  // Include all transaction, component, sequence, and test files
  `include "eth_transaction.sv"
  
  `include "host_agent_config.sv"
  `include "host_driver.sv"
  `include "host_monitor.sv"
  `include "host_sequencer.sv"
  `include "host_agent.sv"

  `include "dma_agent_config.sv"
  `include "dma_driver.sv"
  `include "dma_monitor.sv"
  `include "dma_sequencer.sv"
  `include "dma_agent.sv"
  
  `include "phy_agent_config.sv"
  `include "phy_driver.sv"
  `include "phy_monitor.sv"
  `include "phy_sequencer.sv"
  `include "phy_agent.sv"

  `include "base_seq_lib.sv"

  `include "reg_seq.sv"
  `include "phy_packet_seq.sv"
  `include "phy_max_packet_seq.sv"
  `include "phy_b2b_packet_seq.sv"
  `include "phy_huge_packet_seq.sv"
  `include "phy_delayed_crc_seq.sv"
  `include "phy_rand_packet_seq.sv"
  `include "phy_promisc_seq.sv"
  `include "phy_addr_match_seq.sv"
  `include "tx_seq_lib.sv"
  `include "rx_seq_lib.sv"
  `include "hd_seq_lib.sv" 
  `include "miim_seq_lib.sv"
  
  `include "scoreboard.sv"
  `include "coverage.sv"
  `include "env.sv"
  
  `include "base_test.sv"
  `include "reg_write_test.sv"
  `include "reg_read_test.sv"
  `include "eth_config_test.sv"
  `include "reg_access_random_test.sv"
  `include "reg_reset_test.sv"
  `include "reg_ro_access_test.sv"
  `include "reg_burst_test.sv"
  `include "tx_min_packet_test.sv"
  `include "tx_max_packet_test.sv"
  `include "tx_full_ring_test.sv"
  `include "tx_random_test.sv"
  `include "tx_huge_packet_test.sv"
  `include "tx_broad_multi_test.sv"
  `include "tx_dly_crc_test.sv"
  `include "rx_simple_test.sv"
  `include "base_rx_test.sv"
  `include "b2b_rx_test.sv"
  `include "rand_rx_test.sv"
  `include "huge_rx_test.sv"
  `include "delayed_crc_rx_test.sv"
  `include "promiscuous_mode_rx_test.sv"
  `include "addr_match_rx_test.sv"
  `include "hd_single_collision_test.sv"  
  `include "hd_max_collision_test.sv"
  `include "late_collision_test.sv"
  `include "backoff_test.sv"
  `include "carrier_lost_test.sv"
  `include "fd_seq_lib.sv"
  `include "tx_pause_test.sv"
  `include "rx_pause_test.sv"
  `include "pause_timer_test.sv"
  `include "err_seq_lib.sv"
  `include "tx_underrun_test.sv"
  `include "rx_overrun_test.sv"
  `include "rx_bad_crc_test.sv"
  `include "rx_invalid_symbol_test.sv"
  `include "rx_short_test.sv"
  `include "rx_dribble_test.sv"
  `include "sys_seq_lib.sv"
  `include "loopback_test.sv"
  `include "interrupt_test.sv"
  `include "speed_mode_test.sv"
  `include "rand_traffic_test.sv"
  `include "throughput_test.sv"
  `include "bd_wrap_test.sv"
  `include "miim_read_write_test.sv"
  `include "miim_walking_one_test.sv"
  `include "miim_scan_test.sv"
  `include "miim_no_preamble_test.sv"
  `include "miim_divider_test.sv"
  `include "miim_error_test.sv"
endpackage

`endif // ETHMAC_PKG_SV