`timescale 1ns/10ps
package wb_can_pkg;
  import uvm_pkg::*;        // Import base UVM library 
  import can_bus_pkg::*;    // Import CAN types for scoreboard
  `include "uvm_macros.svh" // Include required macros 

  // Wishbone components
  `include "wb_can_trans.sv"
  
  // Typedef for the sequencer
  typedef uvm_sequencer #(wb_can_trans) wb_can_sequencer;

  `include "wb_can_driver.sv"
  `include "wb_can_monitor.sv"
  `include "wb_can_agent.sv"
  `include "wb_can_scoreboard.sv"
  `include "wb_can_coverage.sv"
  `include "can_tx_coverage.sv"
  `include "can_rx_coverage.sv"
  `include "can_prot_coverage.sv"
  `include "can_err_coverage.sv"
  `include "wb_can_env.sv"

  // Include sequences
  `include "wb_can_single_access_seq.sv"
  `include "wb_can_burst_like_seq.sv"
  `include "wb_can_clk_div_seq.sv"
  `include "wb_can_fifo_addr_map_seq.sv"
  `include "wb_can_fifo_rx_seq.sv"
  `include "wb_can_mode_switch_seq.sv"
  `include "wb_can_reg_access_seq.sv"
  `include "wb_can_reg_reset_seq.sv"
  `include "wb_can_reg_ro_seq.sv"
  `include "wb_can_reset_mode_lock_seq.sv"
  `include "wb_can_reset_stress_seq.sv"
  `include "can_tx_sff_seq.sv"
  `include "can_tx_eff_seq.sv"
  `include "can_tx_rtr_seq.sv"
  `include "can_tx_dlc_rand_seq.sv"
  `include "can_tx_self_rx_seq.sv"
  `include "can_tx_single_shot_seq.sv"
  `include "can_tx_abort_seq.sv"
  `include "can_tx_data_integrity_seq.sv"
  `include "can_tx_burst_transmit_seq.sv"
  `include "can_rx_frame_seq.sv"
  `include "can_bit_stuff_seq.sv"
  `include "can_hard_sync_seq.sv"
  `include "can_resync_sjw_seq.sv"
  `include "can_arb_std_seq.sv"
  `include "can_arb_ext_seq.sv"
  `include "can_alc_capture_seq.sv"
  `include "can_ifs_seq.sv"
  `include "can_overload_seq.sv"
  `include "can_ecc_capture_seq.sv"
  `include "can_err_cnt_warning_seq.sv"
  `include "can_state_transition_seq.sv"
  `include "can_bus_off_recovery_seq.sv"
  `include "can_ack_error_seq.sv"
  `include "can_crc_error_seq.sv"
  `include "can_bit_error_seq.sv"
  `include "can_stuff_error_seq.sv"
  `include "can_form_error_seq.sv"
  `include "can_reactive_err_seq.sv"

  // Tests
  `include "wb_can_single_access_test.sv"
  `include "wb_can_burst_like_test.sv"
  `include "wb_can_reset_stress_test.sv"
  `include "wb_can_reg_access_test.sv"
  `include "wb_can_reg_reset_test.sv"
  `include "wb_can_reg_ro_test.sv"
  `include "wb_can_reset_mode_lock_test.sv"
  `include "wb_can_mode_switch_test.sv"
  `include "wb_can_fifo_addr_map_test.sv"
  `include "wb_can_fifo_rx_test.sv"
  `include "wb_can_clk_div_test.sv"
  `include "can_tx_sff_test.sv"
  `include "can_tx_eff_test.sv"
  `include "can_tx_rtr_test.sv"
  `include "can_tx_dlc_rand_test.sv"
  `include "can_tx_self_rx_test.sv"
  `include "can_tx_single_shot_test.sv"
  `include "can_tx_abort_test.sv"
  `include "can_tx_data_integrity_test.sv"
  `include "can_tx_burst_transmit_test.sv"
  `include "can_rx_base_test.sv"
  `include "can_rx_single_filter_test.sv"
  `include "can_rx_dual_filter_test.sv"
  `include "can_rx_masking_test.sv"
  `include "can_rx_rejection_test.sv"
  `include "can_rx_overrun_test.sv"
  `include "can_rx_rmc_test.sv"
  `include "can_rx_release_test.sv"
  `include "can_rx_rtr_test.sv"
  `include "can_rx_integrity_test.sv"
  `include "can_bit_stuff_test.sv"
  `include "can_hard_sync_test.sv"
  `include "can_resync_sjw_test.sv"
  `include "can_arb_std_test.sv"
  `include "can_arb_ext_test.sv"
  `include "can_alc_capture_test.sv"
  `include "can_ifs_test.sv"
  `include "can_overload_test.sv"
  `include "can_ecc_capture_test.sv"
  `include "can_err_cnt_warning_test.sv"
  `include "can_state_transition_test.sv"
  `include "can_bus_off_recovery_test.sv"
  `include "can_ack_error_test.sv"
  `include "can_crc_error_test.sv"
  `include "can_bit_error_test.sv"
  `include "can_stuff_error_test.sv"
  `include "can_form_error_test.sv"
  `include "can_reactive_err_test.sv"
  `include "can_gap_closer_test.sv"

endpackage
